spring.application.name=EventManagementSystem 
server.port=8081

jwt.secret=3f2e4b5c6d7a8e9f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z0a1b2c3d

# Datasource Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/JPATest
spring.datasource.url=jdbc:mysql://localhost:3306/JPATest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

